### PR TITLE
chore: allow Travis to deploy to staging

### PR DESCRIPTION
**Pull request by ojongerius**
Adds a deployment script that checks if a branch should be deployed, and if so; where. Currently will only deploy on the development branch, to my private AWS account.

@raisedadead what's the history behind using `staging` as the default branch for freecodecamp projects?

I'm not sure if I like having develop *and* staging *and* production (or: master). Is this something you guys have chatted about in the past?

How about having `develop` as the default branch, and having a master (or branch by the name of production) to be used for production deployments?

/cc @QuincyLarson and @Bouncey anything you'd like to add to this discussion?

### CODE REVIEW

**Comment by ojongerius** [comment]
Just thought of having deployment notifications too, I just need admin access to the repository hook it all up.

I figure we'd like to know about deployments in the open-api room, for development, but for prod we *probably* want to notify a larger audience. Would the contributors room be the right place?

**Comment by Bouncey** [comment]
The contributors room would be appropriate. I can add any hooks you need, just send them via signal :+1:

**Comment by raisedadead** [comment]
I am open to having an additional `develop` as a default branch. 
`staging` should always be what we refer as "beta" and `master` should only be used in that case for a release only branch that can be "deploy-able" any time as a production.

**Comment by ojongerius** [comment]
Right so staging is the portal to master, which is production. I'm not sure if we really need a develop branch in that case.

A question I have; what conditions must be met for us to promote a deployment from staging to master (ie: production)? What happens at the moment?

**Comment by ojongerius** [comment]
While we have this discussion I'll merge these changes in. I've raised #50 for the announcements.

**Comment by raisedadead** [comment]
For all intents and purposes, we have a manual deploy from `staging` and and `master` on the main site (actually its `backup\master`, with delay for beta development).

This was so, that we were sure of what is being deployed.

I recommend if you are in agreement that we should keep the deployment from `master` on open-api as manual and `staging` which is to be considered the development branch automated for automated tests and so on.

**Comment by ojongerius** [comment]
@raisedadead what does manual mean here? Is it triggered by a push -ie; a push to master deploys, or does a human run a script?

**Comment by raisedadead** [comment]
The later, a script that needs auth for running against AWS. Like via AWS CLI etc.

**Comment by ojongerius** [comment]
Thanks!

**Comment by ojongerius** [comment]
Last question that was still open:

A question I have; what conditions must be met for us to promote a deployment from staging to master (ie: production)? What happens at the moment?

@raisedadead, @Bouncey do you have an answer?

**Comment by QuincyLarson** [comment]
@ojongerius Currently, production and staging are so different that we essentially maintain two separate codebases. We manually deploy both of production and beta by SSH'ing into the servers, pulling down the latest version of backup/master or staging respectively, then running a pm2 graceful reload.

With this big refactor we are all working on, we'll basically throw away our old master and promote the a staging build to master. 

We have already automated the deployment of Learn and Guide using Travis and Netlify. I think we'll be able to do this for the Welcome page and settings/profiles once we make them static as well. 

As far as deploying updates to the API that powers all of these, I'm open to your suggestions. It would be nice if we had an even more comprehensive test suite that ran against the API, then auto-deployed.

**Comment by ojongerius** [comment]
Thanks for you input @QuincyLarson. We could do the following:

* Consumers have run tests that validate that their queries are able to be fulfilled. A lightweight approach is fetching the production schema and validate the queries are still valid. A more robust approach actually calls the API and validates result are as expected.
* The API pulls down graphq queries from consumers and validates they can still be fulfilled using introspection.
* End do end tests run against both staging and production. Releases soak until at least n end to end tests ran. While this won't catch all edge cases, in a more complicated microservices architecture I expect this to be a good safety net next contract the contract based testing described above.

**Comment by QuincyLarson** [comment]
@ojongerius that sounds like a robust approach to this.

So a couple questions about how this will work in practice:

- will deploys still be fully automatic?
- will we be able to trigger consumers running the tests upon deploying a new version of the API?

**Pull request merged**
