### PR TITLE
chore(refactor): move project files in to src directory

### PR DESCRIPTION
**Pull request by ojongerius**
The root folder got a little unwieldy for my taste, this:

*  keeps integration tests in `test`
* moves all code that we compile and package using webpack in `src`
* keeps the rest in the root

I'm not particular about this structure, what are some of the best practices that you folks like?

### CODE REVIEW

**Comment by raisedadead** [comment]
I for one like this direction, its cleaner this way.

**Comment by ojongerius** [comment]
@Bouncey happy for this to go in?

**Comment by Bouncey** [comment]
Man, my rebase is going to be a nightmare!

**Review by Bouncey — APPROVED** [review]

**Comment by ojongerius** [comment]
Sorry dude!

**Pull request merged**
