### PR TITLE
feat: increase verbosity of Jest

### PR DESCRIPTION
**Pull request by ojongerius**
I like seeing which tests ran.

Currently:

```sh
▶ JWT_CERT=test jest
 PASS  test/integration/users.test.js
 PASS  graphql/resolvers/directive.test.js

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.603s, estimated 2s
Ran all test suites.
```

With `--verbose`:

```sh
▶ JWT_CERT=test jest --verbose
 PASS  test/integration/users.test.js
  ✓ should return null users and auth error without a token (45ms)
  ✓ should return null users and auth error with an invalid token (3ms)
  ✓ should return a user after one has been created (42ms)

 PASS  graphql/resolvers/directive.test.js
  isAuthenticatedOnField
    ✓ should return null if authenication fails (4ms)
    ✓ should return the secretValue if authentication succeeds
  isAuthenticatedOnQuery
    ✓ should throw an error is auth fails (1ms)
    ✓ should call next if auth succeeds

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.534s, estimated 2s
Ran all test suites.
```

### CODE REVIEW

**Review by Bouncey — CHANGES_REQUESTED** [review]
And here, ladies and gentlemen, we a developer that likes to see green ticks when testing.

Me too, thanks!

I would say that we don't need it in CI though. Once the CI log becomes too long, travis starts to just not show the output and offers a raw log output in its place.

So
local -> yes verbose
CI -> no verbose

If a test errors, jest is quite kind in letting you know which line of which test suite failed, which is plenty for CI.

**Comment by raisedadead** [comment]
Well I would like to have it the other way actually. 

CI Mode -> always verbose
Local Mode -> optional verbose

My thinking is:

As a dev, I want to run my tests quickly first, 
```
{
  "test": "cross-env JWT_CERT=test jest"
}
```

if I fail some tests, ONLY then I want to do that in verbose mode to pin-point the issue

```
{
  "test-verbose": "cross-env JWT_CERT=test jest --verbose"
}
```

and with CI I always want verbose, because with that any one can pin-point failing builds.

AND, to address Travis truncating results, as we have seen in on the main repo, I propose to have build stages/suits instead. Separating things as needed into smaller parallel builds.

If we have huge build logs, we clearly need to optimize, than to repeat mistakes from the main repo. There are various options parallel builds, and build stages are just one option. 

Test suits like https://ava.li are others.

**Comment by ojongerius** [comment]
I always enjoy seeing which tests are running in CI, and with the small amount of tests we have at the moment, defaulting to verbosity has my preference.

Completely guilty of enjoying watching those feel-good green checkmarks roll by 😄 

Another plus is that we can go back in time, and see how long individual tests took, in older builds.

**Review by Bouncey — APPROVED** [review]
Seems that @ojongerius has struck a middle ground

**Pull request merged**
