### PR TITLE
chore(dependencies): update lockfile and package formatting

### PR DESCRIPTION
**Pull request by raisedadead**
fixup the package and lockfile from CLI via npm install

### CODE REVIEW

**Comment by raisedadead** [comment]
On that note, I would be happy to switch over to yarn instead. Thought appreciated.

**Comment by ojongerius** [comment]
I think I pushed the same change in #60 😆

**Comment by ojongerius** [comment]
I'd be happy to start using Yarn!

I guess the use case is a little less compelling now that NPM has a lock file. However the speed difference still looks compelling when node_modules and a lockfile are present -judging by some of the results at https://github.com/pnpm/node-package-manager-benchmark .

@Bouncey anything to add?

**Comment by Bouncey** [comment]
`yarn` does things that are nice like `--prune` automatically, which is manual only in `npm`. Plus you get shorter script commands: `npm run format` becomes `yarn format` 

Yay for `yarn`!

**Pull request merged**
