### PR TITLE
refactor(unit tests): DRY up the unit tests for invalid community events

### PR DESCRIPTION
**Pull request by utsab**
This is a fix for #188.  We're looking for feedback on this refactor to DRY up the unit tests.  Please let us know if we are going in the right direction.  Thank you.

### CODE REVIEW

**Review by ojongerius — APPROVED** [review]
LGTM 👍

**Comment by ojongerius** [comment]
This will need f32d0b79d6a5f21472accda68e01bfe13b70ac1f to go green

**Comment by ojongerius** [comment]
@utsab could you please merge staging or cherry-pick f32d0b79d6a5f21472accda68e01bfe13b70ac1f?

**Comment by ValeraS** [comment]
@ojongerius close/open PR to update config in Travis CI

**Comment by ojongerius** [comment]
@ValeraS that commit went in via https://github.com/freeCodeCamp/open-api/pull/199.

**Comment by ValeraS** [comment]
@ojongerius It doesn't matter

**Comment by ojongerius** [comment]
@ValeraS I'm not sure what you mean, could please elaborate?

**Comment by ValeraS** [comment]
~~@ojongerius I see, You do not merge it yet.~~

**Comment by ValeraS** [comment]
@ojongerius If close/open PR Travis CI will start a new build and take for this build config from the master branch.

Restart build in Travis CI UI does not update config.

**Comment by ojongerius** [comment]
@ValeraS aha! Nice trick 👍

**Comment by ValeraS** [comment]
@ojongerius After updating the configuration or if the cofig is up to date, you can simply restart the build in Travis itself, if you need to. No need to close/open PR.

**Pull request merged**
