### PR TITLE
Setup Snyk.

### PR DESCRIPTION
**Pull request by ojongerius**
@raisedadead any suggestions? How do we set this up at snyk.io -guessing that requires GH membership or even admin.

- [ ] Configure and monitor using Snyk
- [ ] Add Snyk badge

### CODE REVIEW

**Comment by raisedadead** [comment]
Hi, we have the main repo configured on snyk.io, we could get this done here too. 

But before proceeding with this, we would need to audit and remove all of the packages that we will not need any more. So, I would recommend waiting on to this for now as well.

**Comment by ojongerius** [comment]
Sure, all for a clean up of the packages 😄

**Comment by raisedadead** [comment]
Lets, close this. I have activated the snyk monitoring utility and it will notify us of issues in two cases:

1. When an PR is adding vulnerabilities with a check as you can see in any PR
2. Send a PR after running a regular CRON everyday (once every 12 hours) if existing dependencies have new vulnerabilities. 

So, we do not need to slow down the CI, or local development because I have found the CLI to be very slow during dev.

That, said we should do two more things:

1. Add the badge to readme. (I'll do that)
2. Add a `npm run` script on the lines of `npm run prepare-production` which will run the CLI when we are on production servers, Deploying stuff. But even this can wait as we are deciding our course of action  here.

**Comment by ojongerius** [comment]
Sure, do you need issues to remind you to add the badge and npm commands?

**Comment by raisedadead** [comment]
Done https://github.com/freeCodeCamp/open-api/issues/29

**Pull request closed without merging**
