### PR TITLE
chore: no more npm

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Review by raisedadead — CHANGES_REQUESTED** [review]
Please consider rebasing against staging to remove the nasty merge commits.

I have just forced updated the staging for a previous merge of https://github.com/freeCodeCamp/open-api/pull/69

```
git pull --rebase upstream staging
git add --all #for resolved conflicts
git rebase --continue 
git push --force
```

This is much better than merging staging. You would still have the same conflicts to resolve. Except for the fact that the commit messages will be clean with steps 2,3 in commands above

**Comment by ojongerius** [comment]
Hey @raisedadead sure! Thanks for schooling me 😁

**Comment by raisedadead** [comment]
Hi @ojongerius sorry about the nit picks... ! But I do owe you a 🍻 for the awesome work with this repo.

**Comment by ojongerius** [comment]
@raisedadead aw thanks! Not used to work repositories with so many commits that this actually becomes an issue 😃

**Comment by ojongerius** [comment]
1 commit, I did it! 🤪

**Comment by raisedadead** [comment]
Nice!

**Pull request merged**
